### ISSUE TITLE
Error when placing a bid

### ISSUE THREAD

**Issue by alexmatson-da** [digital-asset/da-marketplace#93]
Encountered this error on DABL when attempting to place a Bid for `0.01` BTC (asset has quantityPrecision of `6`), and received this error:

```
"io.grpc.StatusRuntimeException: 
INVALID_ARGUMENT: Command interpretation error in LF-DAMLe: 
Interpretation error: 
Error: Update failed due to precondition violation when creating Marketplace.Trading:OrderRequest@6d082c94 with Marketplace.Trading:OrderRequest@6d082c94
{ 
order = Marketplace.Trading:Order@6d082c94{ 
exchange = 'ledger-party-63a46fd4-33f9-4b62-beef-5a89b6deb449', 
exchParticipant = 'ledger-party-afa51818-0a60-4421-a16c-fe4799329ee1', 
pair = DA.Types:Tuple2@40f45226{
 _1 = DA.Finance.Types:Id@6d082c94{ 
signatories = DA.Next.Set:Set@cd314fc5{ 
textMap = TextMap(ledger-party-59999718-fc75-419b-8931-4a13e697f7a3 -> <unit>) }, 
label = "USD", version = 0 }, 
_2 = DA.Finance.Types:Id@6d082c94{ 
signatories = DA.Next.Set:Set@cd314fc5{ 
textMap = TextMap(ledger-party-59999718-fc75-419b-8931-4a13e697f7a3 -> <unit>) 
}, 
label = "BTC", version = 0 } }, 
isBid = true, 
price = 10000.0000000000, 
qty = 0E-10, 
depositCid = #000000000000003c:9, 
status = "New", 
orderId = -1 } }.
```

The precondition that fails is `ensure order.qty > 0.0`, and as we see from the output dump `qty = 0E-10`.

The depositCid listed (`#000000000000003c:9`) _does_ correctly have the asset quantity of `0.01`, so it must be getting mangled into 0 somewhere before/during the `Order` template is created.

**Comment by dimitri-da** [comment]
@alexmatson-da 
Your pair seems to be USD/BTC which means you are trading bitcoin denominated dollars (instead of BTC/USD - dollar denominated bitcoins).

A price of 10000 means *10000 bitcoins per dollar* and if you are only bidding with 0.01 BTC you are effectively trying to buy 0.000001 USD.

If we assume that the quantity precision of USD is 2 (or anything less than 6), the 0.000001 USD was rounded down to 0.00 USD triggering the precondition violation.

**Comment by alexmatson-da** [comment]
Oh, yes I had the pair swapped. Not a bug, then!
